server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:cosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
  mustache:
    cache=false:

jpa:
    hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl